### ISSUE TITLE
Close (modern 2f) authentication window

### ISSUE THREAD

**Issue by BDein** [nbelyh/svgpublish-templates#26] opened 2020-03-23 11:51 UTC
As I wrote you on March 9th we got a new issue on the 2f authentication
 
The login still seems to work, but your add-in don’t seem to “catch” it right, as I doesn’t close the screen that pops up, as you see below:
![image](https://user-images.githubusercontent.com/25555274/77313859-e8211380-6d04-11ea-806c-3bff94f0ed7e.png)
How is it going with this issue?

**Comment by nbelyh** [comment] 2020-03-23 11:56
This is a duplicate of this one: #20
Dear @BDein are you sure you have installed the latest build..?
Could you please check the release number- It should be 1.2.12.**215**

**Comment by BDein** [comment] 2020-03-23 16:45
I have now managed to get the old version uninstalled as Admin, and got the new (215) installed as personal, and it seems to work fine - while saying I've only tested once yet.

**Comment by nbelyh** [comment] 2020-03-27 12:37
Closing as verified

**Closed by nbelyh** 2020-03-27 12:37 UTC
Labels: duplicate
